[package]
name = "ffnn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
rand = "0.8.5"
ndarray-rand = "0.14.0"
image = "0.24.8"
plotters = "0.3.3"
